/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package api

import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import org.springframework.web.bind.annotation.RestController

@RestController
@Validated
@RequestMapping("\${api.base-path:}")
interface KoogApi {
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/api/koog/strategy/graph"],
        produces = ["text/plain"],
    )
    suspend fun getStrategyGraph(): ResponseEntity<String>
}