/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.example.app.api

import com.example.app.api.model.Answer
import com.example.app.api.model.ChatRequest
import jakarta.validation.Valid
import jakarta.validation.constraints.Pattern
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
@RequestMapping()
interface ChatApi {
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/api/chat"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    suspend fun chat(
        @Valid @RequestBody chatRequest: ChatRequest,
        @RequestHeader(value = "X-Session-ID", required = false) xSessionID: String?,
    ): ResponseEntity<Answer>

    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/api/version"],
        produces = ["text/plain"],
    )
    suspend fun getVersion(): ResponseEntity<String>
}