/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Käuferdaten zu einem Auftrag, Bestellung
 *
 * @param name Name der Firma
 * @param customer 
 */


data class Buyer (

    /* Name der Firma */
    @get:JsonProperty("name")
    val name: kotlin.String? = null,

    @get:JsonProperty("customer")
    val customer: Customer? = null

) {


}

