/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package de.itscope.api.dto

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param fields 
 */


data class RowTransformerObject (

    @get:JsonProperty("fields")
    val fields: kotlin.collections.List<IExportFieldObject>? = null

) {


}

